name: CI
on: [commit, push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: npm test
      with:
        jestArgs: src/*.test.js